server:
  port: 9527

spring:
  application:
    name: cloud-zuul-gateway


#把客户端注册到服务列表中
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/
  #设置入驻的服务的名称，是唯一的
  instance:
    instance-id: gateway-9527.com
    #访问路径显示ip
    prefer-ip-address: true

#配置微服务代理
zuul:
  #设置统一的前缀
  prefix: /springcloud
  routes:
    #指定要代理的微服务名称
    myuser.serviceId: cloud-provider
    #指定代理的路径
    myuser.path: /myuser/**
  #忽略真实的服务名，即不能使用服务名访问，只能通过代理访问以保证安全
  #忽略单个微服务
  ignored-services: cloud-provider
  #批量忽略微服务
#  ignored-services: "*"
